spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a13979561749a.
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/xyh?useSSL=false&testOnBorrow=true&testWhileIdle=true